# Generated by Django 5.2.9 on 2026-01-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_analysis_business_type_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='title',
            field=models.CharField(blank=True, default='Untitled Analysis', max_length=200),
        ),
    ]
